services:
    flickr.search:
        class: Desarrolla2\FrontendBundle\Service\FlickrSearchService
        arguments: ['@image.collection']
    image.collection:
        class: Desarrolla2\FrontendBundle\Collections\ImageCollection